github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/app-monitoring-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/apache-skywalking", "gcr.io/paketo-buildpacks/apache-skywalking"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   skywalking-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/skywalking-dependency:main
