# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the Apache SkyWalking Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/apache-skywalking"
  id = "paketo-buildpacks/apache-skywalking"
  keywords = ["apache-skywalking", "agent", "apm"]
  name = "Paketo Buildpack for Apache SkyWalking"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:skywalking:9.5.0:*:*:*:*:*:*:*"]
    id = "skywalking-java"
    name = "Apache SkyWalking Java Agent"
    purl = "pkg:generic/apache-skywalking@9.5.0"
    sha256 = "5ce3d3a97e4403ac3c0c386c211521d0e39237ae1ce662427d1fe8a9bbc20735"
    source = "https://archive.apache.org/dist/skywalking/java-agent/9.5.0/apache-skywalking-java-agent-9.5.0-src.tgz"
    source-sha256 = "07166b8d123c1e725c116c5e1243a0e689b16407bc81d2c5c69b389af3479b32"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/skywalking/java-agent/9.5.0/apache-skywalking-java-agent-9.5.0.tgz"
    version = "9.5.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
