# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the Apache SkyWalking Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/apache-skywalking"
  id = "paketo-buildpacks/apache-skywalking"
  keywords = ["apache-skywalking", "agent", "apm"]
  name = "Paketo Buildpack for Apache SkyWalking"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:skywalking:9.1.0:*:*:*:*:*:*:*"]
    id = "skywalking-java"
    name = "Apache SkyWalking Java Agent"
    purl = "pkg:generic/apache-skywalking@9.1.0?arch=amd64"
    sha256 = "79ce1808965163c939ab34fc411ca444b129f81454c7d4a56d626560219d7280"
    source = "https://archive.apache.org/dist/skywalking/java-agent/9.1.0/apache-skywalking-java-agent-9.1.0-src.tgz"
    source-sha256 = "bf74c260ad75307a531dbd4ffc22d1ede87f42e31e0ba65ec66ede0aac67c4de"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://archive.apache.org/dist/skywalking/java-agent/9.1.0/apache-skywalking-java-agent-9.1.0.tgz"
    version = "9.1.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
